 const currencyOptions = [
  { value: "INR", label: "INR (₹)", symbol: "₹", rateToINR: 1 },
  { value: "USD", label: "USD ($)", symbol: "$", rateToINR: 83 },
  { value: "EUR", label: "Euro (€)", symbol: "€", rateToINR: 90 },
  { value: "GBP", label: "Pound (£)", symbol: "£", rateToINR: 105 },
  { value: "AED", label: "Dirham (د.إ)", symbol: "د.إ", rateToINR: 22.6 },
  { value: "JPY", label: "Yen (¥)", symbol: "¥", rateToINR: 0.57 },
  { value: "CAD", label: "Canadian Dollar (C$)", symbol: "$", rateToINR: 61 },
  { value: "AUD", label: "Australian Dollar (A$)", symbol: "$", rateToINR: 56 },
  { value: "SGD", label: "Singapore Dollar (S$)", symbol: "$", rateToINR: 61 },
  { value: "CNY", label: "Yuan (¥)", symbol: "¥", rateToINR: 11.5 },
  { value: "HKD", label: "Hong Kong Dollar (HK$)", symbol: "$", rateToINR: 10.6 },
  { value: "KRW", label: "Won (₩)", symbol: "₩", rateToINR: 0.063 },
  { value: "ZAR", label: "Rand (R)", symbol: "R", rateToINR: 4.7 },
  { value: "BRL", label: "Real (R$)", symbol: "R$", rateToINR: 16.2 },
  { value: "RUB", label: "Ruble (₽)", symbol: "₽", rateToINR: 0.92 },
  { value: "TRY", label: "Lira (₺)", symbol: "₺", rateToINR: 2.6 },
  { value: "SAR", label: "Saudi Riyal (ر.س)", symbol: "ر.س", rateToINR: 22.1 },
  { value: "MYR", label: "Ringgit (RM)", symbol: "RM", rateToINR: 17.6 },
  { value: "THB", label: "Baht (฿)", symbol: "฿", rateToINR: 2.3 },
  { value: "NZD", label: "NZ Dollar (NZ$)", symbol: "$", rateToINR: 51 },
  { value: "IDR", label: "Rupiah (Rp)", symbol: "Rp", rateToINR: 0.0052 },
  { value: "PHP", label: "Peso (₱)", symbol: "₱", rateToINR: 1.45 },
  { value: "CHF", label: "Swiss Franc (Fr.)", symbol: "Fr.", rateToINR: 95 },
  { value: "SEK", label: "Swedish Krona (kr)", symbol: "kr", rateToINR: 7.6 },
  { value: "NOK", label: "Norwegian Krone (kr)", symbol: "kr", rateToINR: 7.9 },
  { value: "DKK", label: "Danish Krone (kr)", symbol: "kr", rateToINR: 12.1 },
  { value: "PLN", label: "Zloty (zł)", symbol: "zł", rateToINR: 21.1 },
  { value: "EGP", label: "Egyptian Pound (ج.م)", symbol: "ج.م", rateToINR: 1.73 },
  { value: "NGN", label: "Naira (₦)", symbol: "₦", rateToINR: 0.056 },
  { value: "KWD", label: "Kuwaiti Dinar (د.ك)", symbol: "د.ك", rateToINR: 269 },
  { value: "QAR", label: "Qatari Riyal (ر.ق)", symbol: "ر.ق", rateToINR: 22.7 },
  { value: "BHD", label: "Bahraini Dinar (ب.د)", symbol: "ب.د", rateToINR: 220 },
  { value: "OMR", label: "Omani Rial (ر.ع.)", symbol: "ر.ع.", rateToINR: 216 },
  { value: "BDT", label: "Taka (৳)", symbol: "৳", rateToINR: 0.71 },
  { value: "PKR", label: "Pakistani Rupee (₨)", symbol: "₨", rateToINR: 0.30 },
  { value: "LKR", label: "Sri Lankan Rupee (₨)", symbol: "₨", rateToINR: 0.028 },
  { value: "VND", label: "Dong (₫)", symbol: "₫", rateToINR: 0.0033 },
  { value: "ILS", label: "Shekel (₪)", symbol: "₪", rateToINR: 22.7 },
  { value: "UAH", label: "Hryvnia (₴)", symbol: "₴", rateToINR: 2.06 },
  { value: "MXN", label: "Mexican Peso (Mex$)", symbol: "$", rateToINR: 4.9 },
  { value: "ARS", label: "Argentine Peso (ARS$)", symbol: "$", rateToINR: 0.089 },
  { value: "COP", label: "Colombian Peso (COL$)", symbol: "$", rateToINR: 0.021 },
  { value: "CLP", label: "Chilean Peso (CLP$)", symbol: "$", rateToINR: 0.088 },
  { value: "PEN", label: "Peruvian Sol (S/)", symbol: "S/", rateToINR: 22.6 },
  { value: "UYU", label: "Uruguayan Peso ($U)", symbol: "$U", rateToINR: 2.1 },
  { value: "MAD", label: "Moroccan Dirham (د.م.)", symbol: "د.م.", rateToINR: 8.2 },
  { value: "KES", label: "Kenyan Shilling (KSh)", symbol: "KSh", rateToINR: 0.64 },
  { value: "GHS", label: "Ghanaian Cedi (₵)", symbol: "₵", rateToINR: 6.3 },
  { value: "CZK", label: "Czech Koruna (Kč)", symbol: "Kč", rateToINR: 3.7 },
];

module.exports = {currencyOptions};